version: '2.3'

services:
  tm:
    build:
      context: .
      dockerfile: Dockerfile.tm
    ports:
      - "8088:80"
    volumes: # specify where index is stored
      - "./index:/index"
    command: [
        "--bleu-rescoring-threshold", "0.05",
        "--index-dir", "/index"
    ]

  adaptive:
    runtime: nvidia
    build:
      context: .
      dockerfile: Dockerfile.marian
    ports:
      - "8089:80"
    volumes: # Specify where marian model is stored
      - "./marian-model:/marian-model"
    command: [
        "--config", "/marian-model/model.npz.yml",
        "--after-batches", "10",
        "--after-epochs", "10",
        "--learn-rate", "0.1",
        "--mini-batch", "15",
        "--workspace", "4000"
    ]

  wrapper:
    build:
      context: .
      dockerfile: Dockerfile.wrapper
    ports:
      - "8087:80"
    command: [
        "--tm-server", "http://localhost:8088",
        "--marian-server", "ws://localhost:8089"
    ]

